name: xlsx_decoder
description: A Excel XLSX decoder/encoder library.
# version: 1.0.0
# homepage: https://github.com/JohnWall2016/xlsx_decoder.git
# author: John Wall <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0
  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
